spring.application.name=loguin
aws.endpoint=http://localhost:4566

server.port=8083
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


spring.profiles.active=local

aws.dynamodb.profile=localstack
aws.dynamodb.region=sa-east-1
aws.dynamodb.endpoint=http://localhost:4566

spring.docker.compose.enabled=false
spring.cloud.compatibility-verifier.enabled=false

jwt.secret.key=Qw3rT6yU9oP2sV5bN8mC1xZ4aS7dF0hJ